version: '3' 

services:
  xwiki:
    image: ghcr.io/smpesnya/sonatype-nexus3:3.68.1-02 
    container_name: nexus
    ports:
      - "8081:8081"
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/preferences
    volumes:
      - /home/docker/nexus3/data:/nexus-data
      - /home/docker/nexus3/preferences:/preferences
